version: '3.7'

services:
  db:
    image: postgres:14.2
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=${DB_DATABASE_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000 --settings=project.settings.prod
    volumes:
      - .:/code
      - .:/static
    environment:
      - APP_SECRET_KEY=${APP_SECRET_KEY}
      - APP_ALLOWED_HOSTS=${APP_ALLOWED_HOSTS}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
      # Bando de dados
      - POSTGRES_NAME=${DB_DATABASE_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${DB_PORT}
    ports:
      - "80:8000"
      - "8000:8000"
    links:
      - db
    depends_on:
      - db
